### ISSUE TITLE
add ignore for resources goal

### ISSUE THREAD

**Issue by pellcorp** [cheleb/m2eclipse-wtp-gdt#2]
Hi,

At the very least add an ignore action for any goals you are not supporting.

**Comment by cheleb** [comment]
Hi,
Now ignoring mergewebxml, do you think I should ignore other goal (I don,t know if they are relevant in pom file).
Thnx

**Comment by pellcorp** [comment]
Hi,

The resource goal is used in projects where you want to copy the minimal set of java code into the jar file.  Not relevant for eclipse, but certainly is for jar files.

**Comment by cheleb** [comment]
Hi 
Done, thanks for reporting.
