### ISSUE TITLE
How about a p2 update site

### ISSUE THREAD

**Issue by pellcorp** [cheleb/m2eclipse-wtp-gdt#3]
Hi,

Any chance you can host a p2 update site with the plugins so I can point my eclipse at it to get updates rather than having to download the zip file?

Would be great if you could post one with the 'resources' exclusion.

Cheers
Jason

**Comment by cheleb** [comment]
Hi,
 For the p2 update site I will to do it asap.
 The latest 0.0.2 excludes the resources

"Imagination is more important than knowledge.": Albert Einstein

**Comment by darrensalomons** [comment]
So is there still any plan to get this on the Eclipse Marketplace?  What loose ends still need to be tied up?

**Comment by cheleb** [comment]
yes, just have to understand how to do this :)

PS: sorry for the last reply (deleted for github) I thought in was for
m2eclipse-ajdt ...

On Wed, Oct 12, 2011 at 6:04 PM, darrensalomons <
reply@reply.github.com>wrote:

> So is there still any plan to get this on the Eclipse Marketplace?  What
> loose ends still need to be tied up?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cheleb/m2eclipse-wtp-gdt/issues/3#issuecomment-2380953

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by darrensalomons** [comment]
Do you know if Google is working to bundle a configurator into their GPE plugin?

**Comment by cheleb** [comment]
With the last version of GEP there is a configurator based on the
maven-eclipse-plugin ( add natures ).

On Wed, Oct 12, 2011 at 6:31 PM, darrensalomons <
reply@reply.github.com>wrote:

> Do you know if Google is working to bundle a configurator into their GPE
> plugin?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cheleb/m2eclipse-wtp-gdt/issues/3#issuecomment-2381296

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by hdave** [comment]
There is an open issue on GWT for a tool such as this:

http://code.google.com/p/google-web-toolkit/issues/detail?id=6908#c2

Within Eclipse choose Window->Preferences->Maven->Discovery->Catalog and you can see a list of connectors and configurators.  Is this ready to be included in the catalog of M2E connectors?

**Comment by cheleb** [comment]
Update site at http://www.orcades.net/updates/m2eclipse-wtp-gdt/2.4.0/
